Add "yes" parameter to apt calls
zephyrproject-rtos/action-zephyr-setup pull request #12
Opened 2024-04-15 11:52 UTC by epneo-sebastianbaier

2024-04-15 12:10 UTC, henrikbrixandersen requested changes
Why the change from `apt-get` to `apt`? The former should be better suited for scripting like this.

2024-04-15 13:18 UTC, epneo-sebastianbaier commented
> Why the change from `apt-get` to `apt`? The former should be better suited for scripting like this.

You are right. I was under the impression that apt was a complete replacement for apt-get, but I have learnt that apt-get should still be used for scripting.

2024-04-15 23:29 UTC, fabiobaltieri approved these changes

2024-04-22 10:37 UTC, epneo-sebastianbaier commented
@henrikbrixandersen Could you please re-review, so this minor change can be merged?

2024-04-24 10:05 UTC, henrikbrixandersen approved these changes

2024-04-24 10:13 UTC, merged