running actions in act required install of cmake
zephyrproject-rtos/action-zephyr-setup pull request #14
Opened 2024-07-19 15:35 UTC by paulfdietrich

This action works fine on github runners, but when I run locally with https://nektosact.com/ it was missing cmake.

2024-07-19 15:43 UTC, fabiobaltieri commented
Hey thanks, could you reword the commit message following https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines? (ignore the "area:" prefix)

2024-07-24 16:18 UTC, fabiobaltieri commented
> Hey thanks, could you reword the commit message following https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines? (ignore the "area:" prefix)

^^ this is still relevant

2024-09-08 16:48 UTC, henrikbrixandersen requested changes

2024-09-08 16:48 UTC, henrikbrixandersen commented on action.yml
> +        west blobs fetch
I don't think this should be done by default.

2025-01-08 15:17 UTC, fabiobaltieri commented
stale

2025-01-08 15:17 UTC, closed without merging